wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1641866340
    t:
      1:
      - 1
      3:
      - 16
      4: 3.8.0
      5: 0.12.9
      8:
      - 5
action_dtype:
  desc: null
  value: numpy.float32
action_repeat:
  desc: null
  value: 1
action_size:
  desc: null
  value: 3
actor_entropy_scale:
  desc: null
  value: 0.001
actor_lr:
  desc: null
  value: 4.0e-05
batch_size:
  desc: null
  value: 50
capacity:
  desc: null
  value: 1000000
category_size:
  desc: null
  value: 20
chunk_length:
  desc: null
  value: 50
class_size:
  desc: null
  value: 20
clip_grad_norm:
  desc: null
  value: 100.0
collect_intervals:
  desc: null
  value: 5
critic_lr:
  desc: null
  value: 0.0001
discount_loss_scale:
  desc: null
  value: 5.0
embedding_size:
  desc: null
  value: 200
env:
  desc: null
  value: breakout
eps:
  desc: null
  value: 0.0001
eval_episode:
  desc: null
  value: 50
expl_decay:
  desc: null
  value: 7000.0
expl_min:
  desc: null
  value: 0.05
free_nats:
  desc: null
  value: 0.0
gamma:
  desc: null
  value: 0.99
horizon:
  desc: null
  value: 10
kl_balance_scale:
  desc: null
  value: 0.8
kl_loss_scale:
  desc: null
  value: 0.1
lambda_:
  desc: null
  value: 0.95
model_dir:
  desc: null
  value: results
model_lr:
  desc: null
  value: 0.0002
obs_dtype:
  desc: null
  value: builtins.bool
obs_shape:
  desc: null
  value:
  - 4
  - 10
  - 10
reward_loss_scale:
  desc: null
  value: 1.0
rnn_hidden_dim:
  desc: null
  value: 200
rssm_node_size:
  desc: null
  value: 200
save_every:
  desc: null
  value: 50000
seed_episodes:
  desc: null
  value: 1000
slow_target_update:
  desc: null
  value: 100
state_dim:
  desc: null
  value: 400
train_every:
  desc: null
  value: 50
train_noise:
  desc: null
  value: 0.4
train_steps:
  desc: null
  value: 2000000
